### ISSUE TITLE
Payload generation

### ISSUE THREAD

**Issue by joeppeeters** [satori-com/tcpkali#68]
I'm using the tcpkali to test the capabilities of our websocket service under high load. We run a binary protocol over the socket. The tool works fine, out of the box 👍. Though, currently we send the same message over and over, which causes our backend to start serving out cached results which skews our measurements.

I'm looking for a way to generate different payloads for each request. Is that something which is going to be supported? Or is there some alternative way I can achieve this?

**Comment by vlm** [comment]
Please read the manual page concerning dynamic regex-driven loads. For example, use `--ws -em '\{re [0-9]{10}}'` would generate a stream of random numbers.

**Comment by joeppeeters** [comment]
I know of the dynamic loads, but I don't see it working for binary messages. Please correct me if I'm wrong.

**Comment by vlm** [comment]
Would you please show the full command line?

**Comment by joeppeeters** [comment]
We currently do just a simple`tcpkali --ws -m "\{ws.binary <payload>} localhost:8080`.

The `payload` is a sample from a binary message we received. The plan is to sample a bunch (a few thousands) of incoming messages. If we then can load them somehow into the load tester to replay them at a certain rate that would be great. 

What actually could work is as simple a being able to specify a folder and read all files in there. That is, if we can control the rate. Currently it seems the when you specify multiple messages they are all send at the same time.
