### ISSUE TITLE
Message not appear in server

### ISSUE THREAD

**Issue by azzahrah** [satori-com/tcpkali#71]
I want to my tcp server with command, 
```
tcpkali --connections 10 192.168.100.23:9003 --message "Helo\r\n"
``
but in my server message Helo not appear... what going on?

when try manually using telnet 9003 my message appear in server

**Comment by parsifal-47** [comment]
Hi, what do you see at your server?
Are connections established?

**Comment by parsifal-47** [comment]
another thing to consider, use maximum verbose level at tcpkali to see what is happening (-vvv)

**Comment by azzahrah** [comment]
@parsifal-47  connection established...  i try send message from WSL this working, my server can receive and messages, but i wonder why server can receive  \r\n charcter even if i added in last message

**Comment by azzahrah** [comment]
@parsifal-47  for TERMINATE (\r\n) charcter problem is missing -e paramter 

``` tcpkali --connection 10 192.168.100.23:9003 --message "Helo\r\n" ```

 change to
``` tcpkali -e --connection 10 192.168.100.23:9003 --message "Helo\r\n" ```

finally working
